DROP TABLE IF EXISTS plants;
DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS shoes;

CREATE TABLE plants (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  plant_type TEXT NOT NULL,
  category TEXT NOT NULL,
  water_freq INT,
  plant_description TEXT
);

CREATE TABLE decks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  deck TEXT,
  colors VARCHAR(5),
  format TEXT,
  rank INT
);

CREATE TABLE shoes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  shoe TEXT,
  brand TEXT,
  miles VARCHAR(5),
  for_trails BOOLEAN
);
